site_name: JeyJey's Cauldron
repo_url: https://github.com/JeyJeys-Cauldron/recipes
repo_name: JeyJeys-Cauldron/recipes
edit_uri: edit/main/recipe-vault/

docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: green
  features:
    - navigation.tabs
    - navigation.instant
  icon:
    logo: material/silverware-fork-knife
  font:
    text: Fira Sans
    code: Fira Code

plugins:
  - search
  - roamlinks
  - exclude:
      glob:
        - _templates/*
      
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.smartsymbols
  - pymdownx.details
  - attr_list
  - admonition
  - footnotes
  - toc:
      permalink: true

extra_css:
  - static/css/custom.css
