name: Make view

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Generate View
        run: |
          # cargo install obsidian-export
          # obsidian-export --version
          # obsidian-export ./recipe-vault/ ./docs/
          cp -r ./recipe-vault/* ./docs
          
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          git add .
          git commit -m "github workflow update" || true
          git push --force origin HEAD:refs/heads/view
