name: Make view

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate View
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          cargo install obsidian-export

          obsidian-export --version
          obsidian-export ./recipe-vault/ ./recipe-export/
          
          git add .
          git commit -m "github workflow update" || true
          git push --force origin HEAD:refs/heads/view
