name: Make view

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate View
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          wget https://github.com/zoni/obsidian-export/releases/download/v21.9.1/obsidian-export_Linux-x86_64
          ./obsidian-export_Linux-x86_64 --version
          ./obsidian-export_Linux-x86_64 ./recipe-vault/ ./recipe-export/
          
          git commit -m "github workflow update" || true
          git push --force origin HEAD:refs/heads/view
